---
- name: Install Mosquitto
  ansible.builtin.apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
    update_cache: true

- name: Ensure Mosquitto is running
  ansible.builtin.systemd:
    name: mosquitto
    state: started
    enabled: true
