---
- name: Ensure OpenSSH server is installed
  ansible.builtin.apt:
    name: openssh-server
    state: present
    update_cache: true

- name: Ensure SSH is running
  ansible.builtin.systemd:
    name: ssh
    state: started
    enabled: true
